{
    "plane": "plane",
    "aircraft": "plane",
    "airplane": "plane",
    "Boeing747": "plane",
    "ship": "ship",
    "vessel": "ship",
    "motorboat": "ship",
    "small vehicle": "small vehicle",
    "car": "small vehicle",
    "sedan": "small vehicle",
    "large vehicle": "large vehicle",
    "truck": "large vehicle",
    "bus": "large vehicle",
    "storage tank": "storage tank",
    "oil tank": "storage tank",
    "water tank": "storage tank",
    "oil tank": "storage tank",
    "water tank": "storage tank",
    "chemical tank": "storage tank",
    "gas holder": "storage tank",
    "silo": "storage tank",
    "pylon": "power tower",
    "transmission tower": "power tower",
    "wind turbine": "wind turbine",
    "windmill": "wind turbine",
    "chimney": "industrial structure",
    "cooling tower": "industrial structure",
    "train": "train",
    "locomotive": "train",
    "railway carriage": "train",
    "freight car": "train",
    "helicopter": "helicopter",
    "rotorcraft": "helicopter",
    "toll booth": "toll station",
    "toll gate": "toll station",
    "pier": "pier",
    "jetty": "pier",
    "wharf": "pier",
    "greenhouse": "greenhouse",
    "vegetable shed": "greenhouse",
    "plastic covered land": "greenhouse",
    "ground track field": "track field",
    "stadium": "track field",
    "tennis court": "small sports court",
    "badminton court": "small sports court",
    "soccer field": "large sports field",
    "baseball diamond": "large sports field",
    "swimming pool": "swimming pool",
    "water park": "swimming pool",
    "small vehicle": "small vehicle",
    "large vehicle": "large vehicle",
    "cargo truck": "cargo truck",
    "plane": "plane",
    "aircraft": "plane",
    "boeing 747": "plane",
    "helicopter": "helicopter",
    "storage tank": "storage tank",
    "oil tank": "storage tank",
    "water tank": "storage tank",
    "power tower": "power tower",
    "transmission tower": "power tower",
    "wind turbine": "wind turbine",
    "industrial chimney": "industrial chimney",
    "solar panel": "solar array",
    "tennis court": "small sports court",
    "basketball court": "basketball court",
    "soccer field": "soccer field",
    "track field": "track field",
    "parking lot": "parking lot",
    "toll station": "toll station",
    "swimming pool": "swimming pool",
    "dense residential": "dense residential",
    "scattered residential": "scattered house",
    "greenhouse": "greenhouse",
    "cargo ship": "cargo ship",
    "container ship": "cargo ship"
}